# src/ingestion/normalizer.py
"""
Markdown Sanitizer Normalizer.
Cleans up messy table artifacts, <br> tags, and missing spaces 
generated by pymupdf4llm.
"""

import re

class TextNormalizer:
    
    def __init__(
        self, 
        lowercase: bool = False,
        remove_extra_whitespace: bool = True,
        normalize_unicode: bool = False,
        fix_ligatures: bool = False
    ):
        self.lowercase = lowercase
        self.remove_extra_whitespace = remove_extra_whitespace
        
    def normalize(self, text: str) -> str:
        """Sanitizes messy Markdown output before chunking."""
        if not text:
            return ""
            
        #Strip out the annoying picture placeholders
        text = re.sub(r'\*\*==> picture.*?<==\*\*', '', text)
        
        #Replace HTML line breaks with actual spaces
        text = text.replace('<br>', ' ')
        
        #Add spaces around Markdown table pipes 
        text = text.replace('|', ' | ')
        
        #Clean up multiple spaces created by our replacements
        if self.remove_extra_whitespace:
            text = re.sub(r' {2,}', ' ', text)
            
        if self.lowercase:
            return text.lower().strip()
            
        return text.strip()
        
    def normalize_for_bm25(self, text: str) -> str:
        """Maintains the BM25 formatting (lowercase, no punctuation)."""
        if not text:
            return ""
            
        text = text.lower()
        text = re.sub(r'[^\w\s\-]', ' ', text)
        text = re.sub(r'\s+', ' ', text)
        return text.strip()